/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserCounterRouteImport } from './routes/user/counter'
import { Route as DomainRegisterRouteImport } from './routes/domain/register'
import { Route as DomainCompleteRouteImport } from './routes/domain/complete'
import { Route as CertsViewRouteImport } from './routes/certs/view'
import { Route as CertsRevokeRouteImport } from './routes/certs/revoke'
import { Route as CertsNewRouteImport } from './routes/certs/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserCounterRoute = UserCounterRouteImport.update({
  id: '/user/counter',
  path: '/user/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainRegisterRoute = DomainRegisterRouteImport.update({
  id: '/domain/register',
  path: '/domain/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainCompleteRoute = DomainCompleteRouteImport.update({
  id: '/domain/complete',
  path: '/domain/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const CertsViewRoute = CertsViewRouteImport.update({
  id: '/certs/view',
  path: '/certs/view',
  getParentRoute: () => rootRouteImport,
} as any)
const CertsRevokeRoute = CertsRevokeRouteImport.update({
  id: '/certs/revoke',
  path: '/certs/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const CertsNewRoute = CertsNewRouteImport.update({
  id: '/certs/new',
  path: '/certs/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certs/new': typeof CertsNewRoute
  '/certs/revoke': typeof CertsRevokeRoute
  '/certs/view': typeof CertsViewRoute
  '/domain/complete': typeof DomainCompleteRoute
  '/domain/register': typeof DomainRegisterRoute
  '/user/counter': typeof UserCounterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certs/new': typeof CertsNewRoute
  '/certs/revoke': typeof CertsRevokeRoute
  '/certs/view': typeof CertsViewRoute
  '/domain/complete': typeof DomainCompleteRoute
  '/domain/register': typeof DomainRegisterRoute
  '/user/counter': typeof UserCounterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certs/new': typeof CertsNewRoute
  '/certs/revoke': typeof CertsRevokeRoute
  '/certs/view': typeof CertsViewRoute
  '/domain/complete': typeof DomainCompleteRoute
  '/domain/register': typeof DomainRegisterRoute
  '/user/counter': typeof UserCounterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certs/new'
    | '/certs/revoke'
    | '/certs/view'
    | '/domain/complete'
    | '/domain/register'
    | '/user/counter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certs/new'
    | '/certs/revoke'
    | '/certs/view'
    | '/domain/complete'
    | '/domain/register'
    | '/user/counter'
  id:
    | '__root__'
    | '/'
    | '/certs/new'
    | '/certs/revoke'
    | '/certs/view'
    | '/domain/complete'
    | '/domain/register'
    | '/user/counter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertsNewRoute: typeof CertsNewRoute
  CertsRevokeRoute: typeof CertsRevokeRoute
  CertsViewRoute: typeof CertsViewRoute
  DomainCompleteRoute: typeof DomainCompleteRoute
  DomainRegisterRoute: typeof DomainRegisterRoute
  UserCounterRoute: typeof UserCounterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/counter': {
      id: '/user/counter'
      path: '/user/counter'
      fullPath: '/user/counter'
      preLoaderRoute: typeof UserCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain/register': {
      id: '/domain/register'
      path: '/domain/register'
      fullPath: '/domain/register'
      preLoaderRoute: typeof DomainRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain/complete': {
      id: '/domain/complete'
      path: '/domain/complete'
      fullPath: '/domain/complete'
      preLoaderRoute: typeof DomainCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certs/view': {
      id: '/certs/view'
      path: '/certs/view'
      fullPath: '/certs/view'
      preLoaderRoute: typeof CertsViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certs/revoke': {
      id: '/certs/revoke'
      path: '/certs/revoke'
      fullPath: '/certs/revoke'
      preLoaderRoute: typeof CertsRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certs/new': {
      id: '/certs/new'
      path: '/certs/new'
      fullPath: '/certs/new'
      preLoaderRoute: typeof CertsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertsNewRoute: CertsNewRoute,
  CertsRevokeRoute: CertsRevokeRoute,
  CertsViewRoute: CertsViewRoute,
  DomainCompleteRoute: DomainCompleteRoute,
  DomainRegisterRoute: DomainRegisterRoute,
  UserCounterRoute: UserCounterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
