/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserCounterRouteImport } from './routes/user/counter'
import { Route as DomainRegisterRouteImport } from './routes/domain/register'
import { Route as DomainCompleteRouteImport } from './routes/domain/complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserCounterRoute = UserCounterRouteImport.update({
  id: '/user/counter',
  path: '/user/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainRegisterRoute = DomainRegisterRouteImport.update({
  id: '/domain/register',
  path: '/domain/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainCompleteRoute = DomainCompleteRouteImport.update({
  id: '/domain/complete',
  path: '/domain/complete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/domain/complete': typeof DomainCompleteRoute
  '/domain/register': typeof DomainRegisterRoute
  '/user/counter': typeof UserCounterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/domain/complete': typeof DomainCompleteRoute
  '/domain/register': typeof DomainRegisterRoute
  '/user/counter': typeof UserCounterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/domain/complete': typeof DomainCompleteRoute
  '/domain/register': typeof DomainRegisterRoute
  '/user/counter': typeof UserCounterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/domain/complete' | '/domain/register' | '/user/counter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/domain/complete' | '/domain/register' | '/user/counter'
  id:
    | '__root__'
    | '/'
    | '/domain/complete'
    | '/domain/register'
    | '/user/counter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DomainCompleteRoute: typeof DomainCompleteRoute
  DomainRegisterRoute: typeof DomainRegisterRoute
  UserCounterRoute: typeof UserCounterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/counter': {
      id: '/user/counter'
      path: '/user/counter'
      fullPath: '/user/counter'
      preLoaderRoute: typeof UserCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain/register': {
      id: '/domain/register'
      path: '/domain/register'
      fullPath: '/domain/register'
      preLoaderRoute: typeof DomainRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain/complete': {
      id: '/domain/complete'
      path: '/domain/complete'
      fullPath: '/domain/complete'
      preLoaderRoute: typeof DomainCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DomainCompleteRoute: DomainCompleteRoute,
  DomainRegisterRoute: DomainRegisterRoute,
  UserCounterRoute: UserCounterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
